### PR TITLE
Upgrade httpclient to 4.5.7 and handle cookies more compliantly

### PR DESCRIPTION
**Pull request by anjackson**
Following #245 this updated to version 4.5.7 of HTTP Client. Currently, this has only been validated using the built-in tests. One test was outdated and was removed.

### CODE REVIEW

**Comment by anjackson** [comment]
I'd ideally like to hear from IA (ping @nlevitt) in case anyone has objections to this going in at the moment?  I think it's a pretty straightforward upgrade, but I'd like to ensure they are at least aware of it, given how core this dependency is to H3 actually doing anything at all!

**Comment by nlevitt** [comment]
I've been following the discussion but I haven't had a chance to do my homework. Since you asked, I'll just pose the questions I have in mind:

1. Have we looked at performance implications of doing `toArray()` frequently?
2. Is the subdomain thing the only implication of switching from `CookieSpecs.BROWSER_COMPATIBILITY` to `CookieSpecs.DEFAULT`? I guess it's the only one that came up in testing?
3. I think RFC6265 existed when I wrote that comment ("XXX I think browsers differ on this behavior"), but browser behavior is the real spec heritrix tries to follow, more so than an RFC. Most likely browsers are more in line with the RFC these days, but have we tested that?

**Comment by ato** [comment]
> Have we looked at performance implications of doing toArray() frequently?

Here's the 4.3.6 HttpClient code:

```java
      final List<Cookie> cookies = new ArrayList<Cookie>(cookieStore.getCookies());
      ...
      for (final Cookie cookie : cookies) {
```

Here's the 4.5.7 HttpClient code:

```java
        final List<Cookie> cookies = cookieStore.getCookies();
        ...
        for (final Cookie cookie : cookies) {
```

`new ArrayList` calls `toArray()` internally, and the new code calls `toArray()` in `iterator()` so they seem roughly equivalent, a single array copy is made either way. So while the array copy could possibly now be avoided in the new version of HttpClient it doesn't seem to be a performance regression.

> Is the subdomain thing the only implication of switching from CookieSpecs.BROWSER_COMPATIBILITY to CookieSpecs.DEFAULT?

It appears that in 4.5.7 BROWSER_COMPATIBILITY is now an alias for DEFAULT and the old behaviour is not available:

https://github.com/aache/httpcomponents-client/blob/4.5.7/httpclient/src/main/java/org/apache/http/impl/client/CookieSpecRegistries.java#L56-L58

There are many changes between 4.3's compat mode and 4.5.7's default mode.

> browser behavior is the real spec heritrix tries to follow, more so than an RFC. Most likely browsers are more in line with the RFC these days, but have we tested that?

So what do browsers do? Apparently a lot of different things (both to the RFC and to each other): https://inikulin.github.io/cookie-compat/

The subdomain thing appears to be test DOMAIN029 with Chrome, Firefox and Safari being RFC6265 compliant on that particular issue but IE and Edge not.

So browsers are not by any means RFC6265-strict but neither is CookieSpecs.DEFAULT (the RFC6265 strict mode is CookieSpecs.STANDARD_STRICT ).

DEFAULT is documented as:
```
    /**
     * The default policy. This policy provides a higher degree of compatibility
     * with common cookie management of popular HTTP agents for non-standard
     * (Netscape style) cookies.
     */
    public static final String DEFAULT = "default";
```

I guess someone could rig up a harness to run HttpClient against that same set of tests and see how close it is to Chrome as presumably the standard to aim for at the moment by virtue of popularity.

**Comment by nlevitt** [comment]
Thanks @ato! Good enough for me!

**Pull request merged**
